spring.profiles.active=dev

# H2 em arquivo (persistente)
spring.datasource.url=jdbc:h2:file:./data/hqs-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Google Books
integration.google.books.url=https://www.googleapis.com/books/v1/volumes?q=intitle:

#viacep
integration.viacep.url=https://viacep.com.br/ws

#pokemonApi
integration.pokedex.url=https://pokeapi.co/api/v2/pokemon/
integration.pokedex.chain.url=https://pokeapi.co/api/v2/evolution-chain/
integration.pokedex.species.url=https://pokeapi.co/api/v2/pokemon-species/

#StormGlass
integration.stormGlass.url=api.stormglass.io
integration.stormGlass.apikey=70bb1d52-06e8-11f1-b82f-0242ac120004-70bb1dac-06e8-11f1-b82f-0242ac120004
integration.stormGlass.params=airTemperature,precipitation,cloudCover,humidity
weather.mock = true